### ISSUE TITLE
How to call 'webex-rss-bot -h'

### ISSUE THREAD

**Issue by aurisnoctis** [darrenparkinson/webex-rss-bot#1]
Hi Darren, the README for this repo gives the following advice

> You can use webex-rss-bot -h to get help

The command `webex-rss-bot` is 'not found' in bash shell when calling it from the root folder nor could I find any executable with that name in the repo. From where and how should I run it exactly? 

Thanks!

**Comment by aurisnoctis** [comment]
`go run ./ -h` works

**Comment by darrenparkinson** [comment]
Oh yeah you’d have to go build to get the executable.
